### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by daoneandonly** [cmda-bt/be-course-20-21#1]
# Package

## Name
Steven Whitton

## Class
Tech2b

## Repo link
https://github.com/daoneandonly/cmda-be

## Summary
I made a Javascript file that returns a one line joke when run through node! I also used the dev-package Browsersync to serve my `index.html` file on multiple browsers!

## Resources used
[NPM package *one-liner-joke*](https://www.npmjs.com/package/one-liner-joke)
[browsersync.io](https://browsersync.io/)

## Any thoughts?
I've had plenty of experience with node and NPM, so this wasn't much of problem to set up! Looking forward to the next weeks! 🎉

**Comment by jonahgoldwastaken** [comment]
Nice job! The only two things I note is the weird browser-sync code in your html document (that is I think unnecessary as the package usually adds the script tag itself, but could be wrong on that) and the bloated gitignore. Great nonetheless, and definitely enough for this first exercise. 😄
