### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by MariaS20** [cmda-bt/be-course-20-21#10]
# Package

## Name
Tess Smit

## Class
Tech2

## Repo link
https://github.com/MariaS20/Backend20-21

## Summary
Nieuwe repo aangemaakt. Npm geïnstalleerd met de packages camelcase en nodemon. Nodemon had alleen aan het einde wat errors dus hier moet ik nog naar kijken. En een .gitignore file toegevoegd zodat mijn node_modules niet worden toegevoegd aan mijn repo. 

## Resources used
https://www.npmjs.com/package/nodemon

**Comment by Jortdus** [comment]
Ik heb gebruik gemaakt van de streamapi node module om van steam gebruikers informatie te kunnen request vanuit de steam API. Daarnaast heb ik gebruik gemaakt van prompt-sync, een module om input vanuit de gebruiker makkelijker te coderen. De gebruiker moet een steamcommunity link als input geven en het programma kan op dit moment bijvoorbeeld de meest recente games tonen in de terminal.

**Comment by TuriGuilano** [comment]
Lekker bezig. Waar loop je tegen aan met nodemon?
