### ISSUE TITLE
Week 3

### ISSUE THREAD

**Issue by christiaanbraun** [cmda-bt/be-course-20-21#100]
# Input

## Name
Christiaan Braun

## Class
tech_2

## Repo link
https://github.com/christiaanbraun/find_a_teammate

## Summary
I linked the database! It works (I think).

## Resources used
https://howtocreateapps.com/how-to-connect-mongodb-atlas-with-node-js-using-mongoose/

## Any thoughts?
This was fun and a nice challenge.

**Comment by jonahgoldwastaken** [comment]
Hey Christiaan,

Ik zie nergens je mongoose code staan. Ik denk dat er iets mis is gegaan met committen ergens, gezien `db.js` helemaal leeg is. Als je dat fixt kan ik je feedback geven.

**Comment by christiaanbraun** [comment]
Hey Jonah,

Ik zit in een andere branch te werken aan mijn DB, check de feature/database. Als het goed is is die uptodate

**Comment by jonahgoldwastaken** [comment]
Yo Christiaan,

Wat een uitslover ben je man met je controllers en models, lekker bezig man!

Je code is netjes opgezet, al is je "controller" meer een router. Controllers zijn koppelstukken _tussen_ de router en het aangewezen model i.p.v. een plek waar je je routes definieert. Als je die twee functionaliteiten kan loskoppelen van je huidige controller, kan je je code naar een nog hoger niveau tillen.

Ga zo door man! 😄

**Comment by christiaanbraun** [comment]
Thank Jonah!

Ik kwam daar dit weekend inderdaad achter en ga ermee aan de slag!
