### ISSUE TITLE
Week 3

### ISSUE THREAD

**Issue by AronPelgrim** [cmda-bt/be-course-20-21#109]
# Input

## Name
Aron Pelgrim

## Class
Tech 2

## Repo link
https://github.com/AronPelgrim/matching-application

## Summary
Ik heb een MongoDB account aangemaakt met daarin een database. Vervolgens heb ik de database connectie opgezet, als het goed is werkt de connectie.

## Resources used
https://www.youtube.com/watch?v=bxsemcrY4gQ

## Any thoughts?
Het was goed te doen nadat ik een goede tutorial had gevonden.

**Comment by jonahgoldwastaken** [comment]
Hey Aron. Puik werk man! Misschien is het nog wat om ervoor te zorgen dat je server niet start wanneer de database verbinding faalt ([dat gebeurt eigenlijk al zie ik](https://github.com/AronPelgrim/matching-application/blob/d0aa5163b385daf7c3569653840f88036caf606e/index.js#L48), maar je zet express wel helemaal op wat niet zou hoeven als je DB het niet doet).
