### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by Steinberg99** [cmda-bt/be-course-20-21#142]
# Package

## Name
Stein Bergervoet

## Class
Tech 4b

## Repo link
https://github.com/Steinberg99/project-tech/ 

## Summary
Deze week ben ik begonnen met het opzetten van de boilerplate van mijn project. Hiervoor ben ik aan de slag gegaan met het installeren van een aantal npm packages (nodemon, camelcase en express). De node_modules folder heb ik ook opgenomen in mijn .gitignore bestand. Deze opdrachten verliepen allemaal vrij soepel. De tweede opdracht "serve" ging ook goed. Wanneer ik naar localhost:4200 ga in mijn browser zie ik dus "Howdy world!" staan.

## Resources used
* Opgegeven studiemateriaal.

## Any thoughts?

**Comment by SamSlotemaker** [comment]
Lekker bezig tot dusver! Laat het vooral weten als je ergens niet uit komt
