### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by Daan-Zwarthoed** [cmda-bt/be-course-20-21#143]
# Package
Nodemon
Moments
Express

## Name
Daan Zwarthoed

## Class
tech 4 b

## Repo link
https://github.com/Daan-Zwarthoed/Blok-Tech-Daan-Zwarthoed

## Summary
Added moment, nodemon and express package and made the github repo

## Resources used
https://nodemon.io/
https://momentjs.com/
https://expressjs.com/en/starter/hello-world.html

## Any thoughts?
Op DLO staat nog de link naar de github repo van jaar 2018-2019. Dit had ik niet door dus was eerst allemaal onnodige dingen aan het maken. Als die link aangepast kan worden kan veel frustratie schelen voor de volgende die dit vak doen...

**Comment by SamSlotemaker** [comment]
Lekker bezig, routes en template werken al zie ik. Ik kan alleen niet helemaal bedenken waarom je 3 verschillende public mappen hebt, welke reden zit hier achter?
