### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by MaylinnK** [cmda-bt/be-course-20-21#144]
# Package

## Name
Maylinn Kwakman

## Class
Tech 4

## Repo link
https://github.com/MaylinnK/Back-end

## Summary
Ik heb het probleem met de root directory gefixed. Verder heb ik de package.json aangemaakt, Camelcase en Nodemon geinstalleerd en de server aangemaakt.

## Resources used
Stackoverflow en demo videos

## Any thoughts?
Het is voor mij nog steeds erg onduidelijk waar Ubuntu precies voor is en hoe dit anders is dan CMD. De demo video's hielpen enorm met het begrijpen van het huiswerk.

**Comment by SamSlotemaker** [comment]
Ubuntu is linux, en windows heeft zijn eigen cmd, in principe kun je er praktisch hetzelfde mee alleen denk ik dat er hier voor linux commands gekozen worden zodat de tutorials voor windows en mac hetzelfde kunnen blijven (durf ik niet met zekerheid te zeggen).  Lekker bezig verder!
