### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by AsaMarjew** [cmda-bt/be-course-20-21#145]
# Package

## Name
Asa Marjew

## Class
Tech6

## Repo link
https://github.com/AsaMarjew/DatingApp2021

## Summary
Github en server setup. 

## Resources used
Github be-course-20-21 resources and linked websites. 
And HTTP server setup: https://www.digitalocean.com/community/tutorials/how-to-create-a-web-server-in-node-js-with-the-http-module

## Any thoughts?
Het huiswerk was een goede introductie voor het beginner met github en het opstarten van een server. Alleen waren sommige opdrachten niet duidelijk, ik kon begrijpen wat er staat maar hoe ik er kwam was een uitzoek werk. 
Misschien handig om ook iets meer theorie te geven over de git en hoe dit in theorie werkt, ik zelf heb mijn vriend die SE studeert gevraagd om een aantal dingen uit te leggen.

**Comment by shabier** [comment]
Hi Asa, goed bezig! Ik vond het fijn om in het begin Git met een GUI te gebruiken (zie [Gitkraken](https://www.gitkraken.com/)). Toen ik het een beetje onder de knie had, was de CLI een stuk duidelijker. 

Editors, zoals visual studio code, kunnen je ook helpen met commits maken (en veranderingen bijhouden). Zie [vscode docs](https://code.visualstudio.com/docs/editor/versioncontrol)

Er zijn ook best goeie projecten die Git visueel uitleggen, zoals bijvoorbeeld: https://agripongit.vincenttunru.com/. 

Laat het weten als je tegen Git issues aan loopt.
