### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by KoenHaagsma** [cmda-bt/be-course-20-21#146]
# Package

## Name
Koen Haagsma

## Class
Tech 5a

## Repo link
https://github.com/KoenHaagsma/MatchingAppHvA

## Summary
Setup node, express, etc. & Github commit.

## Resources used
Express docs, node docs, nodemon docs.

## Any thoughts?
Dit ging mij vrij goed af, is niet de eerste keer dat ik dit doe.

**Comment by Vuurvos1** [comment]
Zie #159 voor de meer upto date feedback
