### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by 123rvb123** [cmda-bt/be-course-20-21#147]
# Package

## Name
Remco van Bruggen

## Class
Tech 5 b

## Repo link
https://github.com/123rvb123/hello-world

## Summary
Ik vond het in het begin een beetje onduidelijk hoe ik de server moest maken. Toen ik naar de additional resources link ging kwam ik er uiteindelijk gelukkig wel uit. Het installeren van de package express ging makkelijk en probleemloos. Ik moest wel even zoeken wat bepaalde commands van de terminal waren. Dat is even wennen hoe je deze moet gebruiken. 

## Resources used
https://expressjs.com/en/starter/hello-world.html
https://www.makeuseof.com/tag/mac-terminal-commands-cheat-sheet/

**Comment by Vuurvos1** [comment]
Hi Remco,
Ik zie dat je al goed onderweg bent.
Ik zie nog wel een `.DS_store` in je repo staan ookal heb je deze wel toegevoegd aan je `.gitignore`, je kun dit fixen door
```bash
git rm -r --cached .
``` 
te doen en  daarna je files weer toe te voegen en pushen met
```bash
git add .
git commit -m "commit message"
git push
```

**Comment by 123rvb123** [comment]
Thanks! Is gelukt
