### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by Marlenevanerp** [cmda-bt/be-course-20-21#148]
# Package

## Name
Marlène van Erp 

## Class
tech-5 A

## Repo link
https://github.com/Marlenevanerp/Skinmatch

## Summary
Ik had het op het begin een beetje problemen met het installeren van express. Hij maakte op een merkwaardige wijze een 2de package.json aan. Uiteindelijk heb ik alles opnieuw gedaan en hulp gevraagd en is het wel gelukt. 

## Resources used
https://expressjs.com/en/starter/hello-world.html
https://www.makeuseof.com/tag/mac-terminal-commands-cheat-sheet/

**Comment by Vuurvos1** [comment]
Hi Marlène,
Je repo ziet er al netjes uit, ik zie nog wel een `.DS_Store` bestand, deze bestanden komen vanuit mac os en zijn niet essentieel dus zou aanraden om deze toe te voegen aan je `.gitignore`. 
Om vervolgens het bestand uit je repo te krijgen kun je het volgende doen:
```bash
// reset je git cache zodat het bestand weg gaat
git rm -r --cached .
// voeg je files opnieuw
git add .
// commit je veranderingen naar github
git commit -m "remove gitignore files"
git push
```
