### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by MarkvHeusden** [cmda-bt/be-course-20-21#150]
# Package

## Name
Mark van Heusden

## Class
Tech 4 A

## Repo link
https://github.com/MarkvHeusden/Matching-app

## Summary
Ik heb beide opdrachten gemaakt. Ik heb de packages Express en Nodemon geïnstalleerd. Ook heb ik binnen de package.json een script toegevoegd voor Nodemon. Ik vond het eerst wel onduidelijk hoe ik alles van mijn repo in VScode kon wijzigen en dit weer pushen, maar ik ben door klasgenoten geholpen.

## Resources used
Ik heb alle bronnen van backend repo gebruikt en heb zelf nog wat filmpjes bekeken op youtube. Deze vond ik het handigst: https://www.youtube.com/watch?v=ENrzD9HAZK4

**Comment by SamSlotemaker** [comment]
Lekker bezig man,
Fijn dat jullie elkaar hebben kunnen helpen in de klas. Je kunt ook altijd mij of Victor even een berichtje sturen als je ergens niet uit komt!
