### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by Txai-HvA** [cmda-bt/be-course-20-21#151]
# Package

## Name
Txai Pereira de Lacerda

## Class
Tech-4b

## Repo link
https://github.com/Txai-HvA/BlokTech

## Summary
Ik heb een "Hello world!" server gemaakt en nodemon, express en camel geïnstalleerd via npm.

## Resources used
https://www.datacamp.com/community/tutorials/git-push-pull
https://medium.com/@nlfernando11/nodejs-ever-wondered-how-require-works-9aedf0c52128
https://www.freecodecamp.org/news/introduction-to-npm-scripts-1dbb2ae01633/
https://answers.sap.com/questions/9526545/global-dependency-vs-local-dependency.html
https://docs.npmjs.com/specifying-dependencies-and-devdependencies-in-a-package-json-file

## Any thoughts?
Het huiswerk vond ik wel te doen. Enige wat mij niet helemaal duidelijk was waren de "run scripts" in de package.json, maar dat werd in de laatste les duidelijk.

**Comment by SamSlotemaker** [comment]
Fijn dat de run scripts duidelijk zijn geworden, ik denk dat dat naarmate het vak vordert ook nog wel iets duidelijk wordt. 
Nice dat je in iedergeval al een response kan sturen vanuit de server, probeer ook nog even of je op eenzelfde manier statische html bestanden zou kunnen sturen!
