### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by StijnvF** [cmda-bt/be-course-20-21#152]
# Package

## Name
Stijn van Fraeijenhove

## Class
Tech-4

## Repo link
https://github.com/StijnvF/Block-Tech

## Summary

Ik ben aan de slag gegaan met het installeren van NPM packages. Ik heb mij eerste local sever opgezet en ik heb alles gepushed naar GitHub

## Resources used
Voor bijna alles kon ik het prima redden met de Github week1 pagina en de bronnen die hier aan gelinkt waren. Ik had wel wat problemen met het pushen naar GIthub en daar heb ik wat sourches voor gezogt. Dit artikel hielp vooral: https://zapier.com/blog/how-to-push-to-github/

## Any thoughts?
Vrij duidelijke opbouw. Fijne info over de onderwerpen. En ook fijn dat je niet alles hoeft te onderzoeken om aan de slag te gaan. Je kan ook gewoon gaan proberen. Dit werkte goed voor mij.

**Comment by SamSlotemaker** [comment]
Probeer je code consistent te houden, je gebruikt nu overal arrow functies in de .get en een normale functie in de .set, ik zou deze ook omzetten naar een arrow functie om het consistent te houden. Lekker bezig wel verder!
