### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by nataschazw** [cmda-bt/be-course-20-21#158]
## Name
Natascha Zwolsman

## Class
tech 4.

## Repo link
https://github.com/nataschazw/bloktech

## Summary
ik heb geleerd over node en express, het verschil tussen de client en server side, over npm, hoe je packages kan toevoegen en kan gebruiken, het verschil tussen dependencies en devdependencies, waar script voor is en hoe je dat kan gebruiken, wat een .gitignore bestand is en wat het doet en hoe ik via mijn terminal wijzigingen kan committen en pushen.

## Resources used
Youtube filmpjes waren heel kort en handig over npm/node/express etc. en de bronnen die week 1 stonden doorgelezen.

## Any thoughts?
Geen! het was een mooie eerste week en de extra les om vragen te stellen is heel handig.

**Comment by SamSlotemaker** [comment]
Lekker bezig Natascha! Probeer je code consistent te houden, je 404 gebruikt een normale functie terwijl je bij de rest array functions (=>) gebruikt, probeer deze naar een lijn te trekken.
