### ISSUE TITLE
Week 2

### ISSUE THREAD

**Issue by KoenHaagsma** [cmda-bt/be-course-20-21#159]
# Package

## Name

Koen Haagsma

## Class

Tech 5

## Repo link

https://github.com/KoenHaagsma/MatchingAppHvA

## Summary

Setting up Pug with all the necessary stuff.
Also setting up the static loader.

Trying to do routing with pug and express.
This actually worked after watching some video's

## Resources used

-   https://www.youtube.com/watch?v=Ad2ngx6CT0M
-   http://expressjs.com/en/guide/using-template-engines.html
-   https://pugjs.org/api/express.html
-   https://expressjs.com/en/guide/routing.html
-   https://www.reddit.com/r/learnprogramming/comments/8hjydr/expressjs_failed_to_lookup_view_error_with/
-   https://expressjs.com/en/starter/faq.html

-   https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet
-   https://expressjs.com/en/starter/faq.html
-   https://expressjs.com/en/starter/static-files.html
-   https://www.youtube.com/watch?v=oWQFsILkVag

## Any thoughts?

It was a bit hard to do but after watching some videos and reading some documentations I managed to do it.

**Comment by Vuurvos1** [comment]
Hey Koen,
Lekker bezig zie ik, je bent al best ver en hebt PUG al werkent zie ik.
Kijk nog even naar je Package.json, ik zie dat handlebars hier nog in staat terwijl je PUG gebruikt en volgens mij kun je met express ook static bestanden serveren en heb je dus geen `serve-static` nodig
Vergeet niet je wiki en readme upto date te houden

**Comment by KoenHaagsma** [comment]
Thx voor de comment @Vuurvos1, ik gebruik serve-static niet at the moment dus heb hem eruit gehaald. Ook heb ik de package.json erop aangepast.

**Comment by KoenHaagsma** [comment]
@Vuurvos1 Wat zou ik precies moeten zetten in m'n readme.md?

**Comment by Vuurvos1** [comment]
Volgens mij gaat dit nog behandeld worden in de les, maar denk aan dingen als wat is dit project, hoe te installeren/gebruiken, liscense, bronnen, enz
