### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by zainuwachtig** [cmda-bt/be-course-20-21#160]
# Package

## Name
Zain

## Class
tech-4

## Repo link
https://github.com/zainuwachtig/blok-tech

## Summary
Ik heb verschillende NPM packages gedownload en met een local server gewerkt.

## Resources used
Ik heb een paar filmpjes van Danny bekeken (https://www.youtube.com/channel/UCnatfVfgim0QIuwjx8-PnEQ) en de resources die bij de opdrachten stonden.

## Any thoughts?
Het ging allemaal wel goed, de opdrachten staan duidelijk uitgelegd. Ik had alleen moeite met mijn lokale repo pushen, maar ik ben daarbij geholpen door een klasgenoot.

**Comment by SamSlotemaker** [comment]
Lekker bezig! Probeer je code consistent te houden, je gebruikt soms een normale functie terwijl je bij de rest ook array functions (=>) gebruikt, probeer deze naar een lijn te trekken.
