### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by Falicer** [cmda-bt/be-course-20-21#162]
# Package

## Name
Raekwon Gerold

## Class
Tech-5

## Repo link
[Project Tech 2021](https://github.com/Falicer/Project_Tech_2021)

## Summary
Nog niet veel, ik moet de installatie en de packaging nog doen en loop daar beetje vast atm. Ik vraag het tijdens de les wel na.

## Resources used
Informatie van de Git guides.

## Any thoughts?
Moet alles ff refreshen, ben alles weer vergeten.

**Comment by Vuurvos1** [comment]
Hi Raekwon,
Je repo is nog erg leeg dus weinig om feedback over te geven. Ben optijd met vragen stellen aan de student assistenten of docenten in plaats van te wachten tot een les. Een paar dingen die je sowieso nog kunt doen zijn een `.gitignore` toevoegen, je readme uitberijden en je wiki vullen met je concept. Vergeet ook niet: Commit Often, Perfect Later
Zet hem op!
