### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by AllyssaA** [cmda-bt/be-course-20-21#164]
# Package

## Name
Allyssa

## Class
tech-5

## Repo link
https://github.com/AllyssaA/matching-app

## Summary
Heb een boilerplate aangemaakt, verschillende packages geïnstalleerd met npm, geleerd wat gitignore precies doet.  

## Resources used
https://github.com/github/gitignore/blob/master/Node.gitignore
https://docs.github.com/en/github/getting-started-with-github/ignoring-files
https://www.youtube.com/watch?v=X8D5Ijpp824
https://www.youtube.com/watch?v=ZpiHUOM_Y-0
https://docs.npmjs.com/cli/v7/configuring-npm/package-json
https://expressjs.com/en/starter/hello-world.html
https://www.youtube.com/watch?v=shSB9BbK1gU

## Any thoughts?
Als je nog nooit met npm of packages hebt gewerkt kan ik me voorstellen dat dit best veel is, de resources die erbij waren gelinkt hebben mij enorm geholpen.

**Comment by Vuurvos1** [comment]
Hi Allyssa,
Je bent al goed opweg, ga zeker zo door.
Ik zie wel dat alle packages die je hebt geinstaleerd hebt dev dependencies zijn, terwijl de meeste dit niet zijn. Dev dependencies zijn voor developers en niet essentieel voor de app, bijvoorbeeld hoe nodemon je app automatisch herstart is heel handig tijdens het maken van je site, maar is niet nodig voor het werken van de app omdat je normaal `express` gebruikt.
