### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by jabirtisou** [cmda-bt/be-course-20-21#166]
# Package

## Name
Jabir Tisoudali

## Class
Tech 4A
## Repo link
https://github.com/jabirtisou/CMDBlokTech

## Summary
Ik heb verschillende npm packages geïnstalleerd en aan de node server gewerkt.

## Resources used
Filmpjes van Danny bekeken.

## Any thoughts?
Ik had problemen met het pushen naar Git. Ik heb mijn repo opnieuw moeten aanmaken. Maar uiteindelijk is het wel gelukt.

**Comment by SamSlotemaker** [comment]
Fijn dat het in iedergeval gelukt is uiteindelijk. Je kunt ook altijd mij en Victor een berichtje sturen als je ergens niet uit komt, als is het maar wat kleins :) 
Ziet er tot dusver goed uit!
