### ISSUE TITLE
Week 2

### ISSUE THREAD

**Issue by Daan-Zwarthoed** [cmda-bt/be-course-20-21#168]
# Templating

## Name
Daan Zwarthoed

## Class
Tech 4 B

## Repo link
https://github.com/Daan-Zwarthoed/Blok-Tech-Daan-Zwarthoed

## Summary
Deze week heb ik pug geïmplementeerd in mijn site en de meeste pagina's die ik nodig heb aangemaakt.

## Vraag
Ik gebruik nu pug dus ik heb dan mijn pug files en de html files die je daar uit krijgt. Ik neem aan dat je 1 van die 2 in je .gitignore moet zetten. Weet jij welke?

## Resources used
https://pugjs.org/

## Any thoughts?
Dit kan aan mij liggen, maar de gegeven bronnen bij de opdracht voor template engine's waren erg onduidelijk. Het koste mij ook echt super lang om het eindelijk aan de praat te krijgen.

**Comment by SamSlotemaker** [comment]
Template engines zijn even nieuw dus het is misschien lastig om ze direct te begrijpen inderdaad. Vooral ook omdat pug gelijk weer een hele andere syntax gebruikt kan het even wennen zijn. Mocht je nu al denken dat het vreselijk wordt, vind ik EJS zelf veel prettiger, doordat deze praktisch dezelfde syntax als html en javascript gebruikt. Ik begrijp niet helemaal wat je bedoelt met de pug en html files, mocht je er nog niet uit gekomen zijn moet je me even een berichtje op teams sturen!
