### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by MartijnvdLans** [cmda-bt/be-course-20-21#171]
# Package

## Name
Martijn

## Class
Tech 4a

## Repo link
https://github.com/MartijnvdLans/Project_tech

## Summary
Ik heb een package.json toegevoegd en hopelijk de juiste bestanden

## Resources used
Filmpje van de lesmateriaal

## Any thoughts?
Ik vond het zelf nu al enorm lastig omdat het niet echt logisch voor me was hoe alles werkte en waar het precies voor diende. Dit is ook de reden dat mijn issue wat later is vergeleken met de rest. Ik was enorm blij dat dit nog herhaald werd ik les 2a zodat ik dit nog goed mee kon volgen.

**Comment by SamSlotemaker** [comment]
Het is niet erg als alles niet in 1 keer duidelijk is, hoe vaker je het gaat zien komende weken hoe logischer het wordt. Probeer je code ook consistent te houden, je gebruikt nu bij je app.use() een normale functie en bij de rest arrow functions (=>), probeer hier 1 lijn in te trekken. Mocht er iets niet lukken of gewoon niet 100% duidelijk zijn, kun je mij en Victor altijd even een berichtje sturen op teams, dan leggen we het nog even uit!
