### ISSUE TITLE
Week 2

### ISSUE THREAD

**Issue by Steinberg99** [cmda-bt/be-course-20-21#172]
# Templating

## Name
Stein Bergervoet

## Class
Klas 4b

## Repo link
https://github.com/Steinberg99/project-tech/

## Summary
Deze week heb ik de templating engine Pug geïnstalleerd in mijn project. Ik heb een simpel begin gemaakt met de pagina's die ik nodig ga hebben en ik heb een aantal components aangemaakt.  

## Resources used
* [Express documentatie](https://expressjs.com/en/guide/using-template-engines.html)
* [Pug documentatie](https://pugjs.org/api/getting-started.html)
* Opgegeven studiemateriaal
 
## Any thoughts?

**Comment by SamSlotemaker** [comment]
Ziet er goed uit man, laat het vooral weten als je ergens tegenaan loopt!
