### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by zara4444** [cmda-bt/be-course-20-21#174]
# Package

## Name
Zahra Ahmadi

## Class
Tech 5B

## Repo link
https://github.com/ZahraAhmadi4/matchingapp-zahra

## Summary
In de eerste week heb ik de package aangemaakt, mij verder ingelezen op de theorie en aan de slag gegaan met het opzetten van de server. Dat is nog niet gelukt. 

## Resources used
Github Backend kanaal en de linkjes die daarin opgegeven waren.

## Any thoughts?
De express server was moeilijk. Het is me nog steeds niet gelukt! De browser kon geen verbinding met de server maken. Ik weet niet wat ik fout doe, maar ik zal morgen even om hulp vragen aan student-assistenten.

**Comment by Vuurvos1** [comment]
Hey Zahra,
Je repo ziet er al netjes uit. In je `package.json` kun je mischien de naam van het `test` script veranderen naar iets als `dev` omdat dit beter beschrijft wat dit script doet. Je kan je readme ook nog aanvullen met dingen als hoe je het project instaleert.
Als iets niet lukt stel optijd vragen aan de docenten/student assistenten, wij zijn er om te helpen. Wacht ook zeker niet te lang met vragen, het is zonde om dagen vast te lopen op iets kleins wat binnen 10 minuten opgelost kan zijn.

**Comment by zara4444** [comment]
Hi!

Dankjewel voor het kijken naar mijn repo! Ah okay, dat van het script, snap ik. Hoe moet ik dat dev dan schrijven? Iets als -> "dev": "app" ? 

En het was mij trouwens gelukt het probleem met de server op te lossen. Bedankt voor je advies, ik zal het onthouden!

Ik hoor nog graag van je of ik dat 'dev' in het script zoals ik het heb beschreven goed is!

**Comment by Vuurvos1** [comment]
In je [package.json](https://github.com/ZahraAhmadi4/matchingapp-zahra/blob/main/package.json#L7) staat onder de scripts `test: nodemon index.js` het is super handig om zo een command te hebben alleen is de naam test niet beschrijvend voor wat het script eigenlijk doet. Als je het veranderst in `dev: nodemon index.js` kun je met `npm run dev` je project starten met nodemon. Je zou op dezelfde manier ook een start script kunnen toevoegen die je app start met `node index.js`

**Comment by zara4444** [comment]
Ah okay... ik snap hem. Ik heb het veranderd. Dank voor je hulp!

**Comment by zara4444** [comment]
Nadat ik het gisteren veranderde naar 'dev' werkt mijn app niet meer. Ik kan de server niet meer openen. Heb je vandaag toevallig tijd om met mij hiernaar te kijken?

**Comment by Vuurvos1** [comment]
Ja prima, stuur maar een berichtje op teams naar Sam de Kanter
