### ISSUE TITLE
Week 2

### ISSUE THREAD

**Issue by julius-gm** [cmda-bt/be-course-20-21#186]
# Templating

## Name
Julius Meeuwisse

## Class
Tech-4

## Repo link
https://github.com/Juliusmeeuwisse/bloktech

## Summary
Ik heb de templating engine gedownload en alvast een paar partials gemaakt. Ik heb een array gemaakt waaruit een willekeurige waarde gekozen wordt die wordt weergegeven op mijn index.ejs pagina. Ik heb de routes verandert naar aanleiding van mijn eigen applicatie

## Resources used
EJS.co, stackoverflow

## Any thoughts?
Het huiswerk was aan het begin een beetje verwarrend voor mij omdat het erg nieuw is maar ik kwam er na wat threads erg goed uit!

**Comment by SamSlotemaker** [comment]
Lekker bezig, fijn dat het gelukt is. Misschien leuker om de random waarde te generen in de '/' route, inplaats van in de globale scope van je server, zodat er ook steeds een andere waarde gekozen wordt wanneer je de pagina opvraagt en niet alleen bij het opstarten van je server
