### ISSUE TITLE
Week 2

### ISSUE THREAD

**Issue by StijnvF** [cmda-bt/be-course-20-21#187]
# Templating

## Name
 Stijn van Fraeijenhove 

## Class
 Tech-4 

## Repo link
https://github.com/StijnvF/Block-Tech 

## Summary
Het serve gedeelte van het huiswerk ging mij vrij gemakkelijk af na de les die we daar over hadden. Bij templating ging het zeker moeilijker. Ik heb daarom ook wat hulp gevraagt aan een student assistent. Maar met deze hulp denk ik dat ik de basis nu redelijk begrijp. 

## Resources used

* block-tech repo
* EJS site
* deze playlist op YT https://www.youtube.com/watch?v=w-7RQ46RgxU&list=PL4cUxeGkcC9gcy9lrvMJ75z9maRw4byYp&index=1

## Any thoughts?
Het zou voor mij heel fijn zijn geweest als de stappen iets duidelijker waren omschreven voor het HW. Het was moeilijk om te starten omdat het hele begrip Templating engines nog  helemaal nieuw was. Bijvoorbeeld bij de stap 3 *Then, render dynamic data using your templating engine. So instead of you writing the .html insert some dynamic data. For example; you can store and array or object on the server and inject data into the view. Later we'll look at how to insert data from a database.* Ik had geen idee hoe ik hier aan moest beginnen omdat de begrippen in zijn algemeenheid niet duidelijk waren voor mij. Ik snap dat ik daar wel achter kom wanneer ik door alle documentatie heen ben gegaan, alleen werkt het een beetje demotiverend om zo'n vraag te zien staan en meteen al te denken hoe ga ik dit ooit doen.

Verder weer veel inzichten gedaan!

**Comment by SamSlotemaker** [comment]
Documentatie lezen is natuurlijk altijd een strak plan, maar schroom ook niet om even een berichtje te sturen op teams! Victor Boucher en ik zijn er om je te helpen, dus ook wanneer je de opdracht niet volledig begrijpt kun je ons altijd even een berichtje sturen!
