### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by Aidan98** [cmda-bt/be-course-20-21#19]
# Package

## Name
Aidan Omwando

## Class
Tech 3

## Repo link
https://github.com/Aidan98/Project-Tech

## Summary
AI created a boilerplate for the matching app, and I installed the package called micromatch to help me create the feature I want to code. And I added some simple run scripts (I still don't have the hang of that).

## Resources used
https://css-tricks.com/why-npm-scripts/
https://www.npmjs.com/package/micromatch

## Any thoughts?
I've got nothing really to add other than that I still don't completely understand "run scripts"

**Comment by victorboucher** [comment]
Hi Aidan, je moet nog even een .gitignore bestand maken en hier je node_modules map in beschrijven. Je wilt namelijk de node_modules map niet op GitHub zetten, dan komt je repo erg snel vol te staan met allemaal onnodige bestanden. Verder zie ik nergens in je repo een JavaScript bestand waarmee je de server start (index.js/app.js).
