### ISSUE TITLE
Week 2

### ISSUE THREAD

**Issue by SamvanderLeek** [cmda-bt/be-course-20-21#194]
# Templating

## Name
Sam van der Leek

## Class
tech-5b

## Repo link
https://github.com/SamvanderLeek/matching-app

## Summary
Deze week heb ik onderzoek gedaan naar templating engines, ik heb gekeken welke verschillende er waren en heb ik er voor mezelf 1 uitgezocht waar ik mee ga werken. 

Ik heb met hulp van Koen en het internet pug uitgeprobeerd.

## Resources used
https://dev.to/nkratzmeyer/html-templating-with-pugjs-7m9

## Any thoughts?
Ik had moeite met de opdrachten van deze week, het duurde allemaal wat langer voordat ik het een beetje door begin te krijgen. Ik heb voor deze week ook langer aan het huiswerk gezeten dan de aangegeven tijd,

**Comment by Vuurvos1** [comment]
Hi Sam,

Je hebt goed ondezoek gedaan naar templating engines en dit genoteerd in je wiki en hebt het volgens mij ook al werkent. Geef misschien alleen wat code voorbeelden met [code blokken ](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code) in je wiki zodat je makkelijker de syntax kunt zien. 
Voor je readme is `Clone het project` mischien niet genoeg informatie, welke link moet ik clonen, wat voor project is dit en wat kan ik ermee, bronnen enz.
Verder ben je goed bezig, vergeet alles niet goed te documenteren maar ga zo door
