### ISSUE TITLE
Week 3

### ISSUE THREAD

**Issue by judithkoelewijn** [cmda-bt/be-course-20-21#196]
# Input

## Name
Judith Koelewijn

## Class
tech-5

## Repo link
https://github.com/judithkoelewijn/matching-application

## Summary
- servers, route en custom 404 gemaakt
- combineren van backend en frontend
- verder werken met handlebars
- stukje prototype gebouwd: formulier waarbij de gebruiker data invult en vervolgens op een custom pagina komt met Hallo {{naam}} etc wat nu ook werkt
- MongoDB gekoppeld (met Compass)
- GitHub Wiki up to date gemaakt: templating onderzoek 
- Nieuwe voortgang gecommit

## Resources used
https://docs.mongodb.com/manual/installation/
https://handlebarsjs.com/guide/#installation

## Any thoughts?
Ik vond de opdracht 'input' erg breed, wat natuurlijk ook logisch is omdat dit volledig afhankelijk is van je eigen feature. Maar ik merkte dat ik hier wel veel meer dan de geschreven 10 uur aan heb besteed omdat het lang duurde voordat ik de juiste richting had gevonden. Maar... toen het eenmaal werkte was het wel super tof.

**Comment by Vuurvos1** [comment]
Hi Judith,

Je bent erg goed opweg met de code van je project maar let een beetje op de netheid van je repo.
Je `.gitignore` is nog leeg, zeg hier dingen in als de `node_modules` folder en `.DS_Store` bestanden omdat deze bestanden niet essentieel zijn voor het werken van je repo of geinstaleerd kunnen worden door via NPM. Als je deze dingen heb toegevoegd aan de `.gitignore` kun je 
```bash
git rm -r --cached .
```
en vervolgens `git add .` en `git commit -m "commit message"` zoals je normaal ook zou doen om de bestanden uit de gitignore ook echt uit je repo te halen [zie deze stackoverflow post](https://stackoverflow.com/questions/50675829/remove-node-modules-from-git-in-vscode)

Verder staan in je `package.json` nog allerlij packages die je niet gaat gebruiken dit project, react bijvoorbeeld. Haal deze packages dan ook weg.

Ga zo door!
