### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by manon-ev** [cmda-bt/be-course-20-21#2]
# Package

## Name
Manon Eveleens

## Class
Tech3 A

## Repo link
https://github.com/manon-ev/Matching.App/tree/main/Lab-1

## Summary
Gewerkt in de terminal in combinatie met Visual Studio Code. Local host gebruikt.

## Resources used
express.com, informatie uit de les en GitHub.

## Any thoughts?
Ik vond het best pittig als eerst opdracht. Vooral als je bugs hebt zijn deze nog lastig op te lossen. Had het niet gekund zonder hulp denk ik.

**Comment by victorboucher** [comment]
Hi Manon, ziet er goed uit! Fijn dat je een .gitignore bestand hebt gemaakt en dat het meeste is gelukt. Ik zie alleen nergens een package.json bestand in je repo. Dit is het bestand waar je NPM configuratie in staat. Heb je deze wel aangemaakt (met npm init)? Want ik zie wel dat je bent begonnen met express.
