### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by Sophievanderburg** [cmda-bt/be-course-20-21#21]
# Package

## Name
Sophie van der Burg

## Class
Tech2b

## Repo link
https://github.com/Sophievanderburg/blok-tech

## Summary
I read all the articles and made notes for myself. This took a long time to finish. Then I did the freecodecamp excercises. This went pretty good actually. Then I started on the assignments. With help of my classmates I managed to do everything. 

## Resources used
You can find all the resources i used on: https://github.com/cmda-bt/be-course-20-21/blob/main/week-1.md 

## Any thoughts?
Many new terms are used in the articles. At least, the terms are new to me. Since everything is quite abstract to me, it was difficult to understand the first time I read it. That is why I had to read almost all articles 2 or 3 times before I roughly understood what was being told. I was able to ask a lot of questions to my classmates. This has helped me a lot. I think I kind of get it now, but I wouldn't put any money on that. :)

**Comment by TuriGuilano** [comment]
Great to hear that your classmates and you formed a team and helped each other out!
