### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by jody29** [cmda-bt/be-course-20-21#24]
# Package

## Name
Jody Lorist

## Class
Tech 2a

## Repo link
https://github.com/jody29/matching_feature

## Summary
For this week, I started by creating my GitHub repository and adding a Readme.md + License file to it. After i've created my repository, I've tried to connect it with Git. I used the recording of the first lecture for this. I think i managed to link my GitHub repository after 30 minutes.

After i've managed to link my github with Git, i've initialized the node_modules directory to my repository. I then installed nodemon, express, react and mongodb. After i installed all these files, I tried to do the learnyounode workshopper. I really had some troubles with these exercises. The first one was doable, but then i had to search on google for the solution.

<img width="542" alt="Schermafbeelding 2021-02-07 om 18 07 54" src="https://user-images.githubusercontent.com/66092262/107153760-847cf480-696f-11eb-86c2-a4831a27be94.png">

## Resources used
https://confluence.atlassian.com/bitbucketserver/basic-git-commands-776639767.html
https://joecreager.com/learnyounode-unofficial-companion/
https://www.tablesgenerator.com/markdown_tables
https://www.cyberciti.biz/faq/linux-append-text-to-end-of-file/
https://smallbusiness.chron.com/previous-directory-mac-terminal-49989.html

## Any thoughts?
I think for the first week, we got a lot of information. This was a bit a lot to handle for me. But I did managed to keep up. I do think that the learnyounode exercises were a bit too hard for week 1.

**Comment by TuriGuilano** [comment]
When you have explicit questions - please do contact @jody29 !
