### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by norakramer1** [cmda-bt/be-course-20-21#27]
# Package

## Name
Nora Kramer

## Class
Tech 1

## Repo link
https://github.com/norakramer1/blokTech

## Summary
Video's bekeken, artikelen gelezen, how-to-npm workshop afgerond, package.json aangemaakt, lodash geïnstalleerd, gitignore gemaakt.

## Resources used

- https://nodejs.dev/learn/the-package-json-guide
- https://docs.npmjs.com/cli/v6/using-npm/scripts
- https://www.npmjs.com/package/lodash
- https://www.youtube.com/watch?v=hHt3oVk3XVk
- https://www.pluralsight.com/guides/how-to-use-gitignore-file

## Any thoughts?
Het installeren van packages was duidelijk, ik wist daarna alleen niet zo goed wat ik er mee moest doen. Hetzelfde met de run scripts, ik weet wat het zijn en waar je ze voor gebruikt maar ik weet niet wat ik er in mijn project mee kan op dit moment dus ik heb er nog niks mee gedaan.

**Comment by SamSlotemaker** [comment]
Goed bezig Nora, dat de scripts en packages nog niet volledig duidelijk zijn is niet zo gek, je gaat deze later een stuk meer gebruiken. In je matching app kan het bijvoorbeeld voorkomen dat je een login formulier gaat handelen en hierbij een stukje 'beveiliging' wilt meenemen in je app. Hiervoor zou je dan een package kunnen zoeken die dit voor jou regelt, zodat je niet alle code zelf hoeft te schrijven. Is inderdaad voor nu nog niet het geval, dus zolang je begrijipt wat het doet en waar het voor gebruikt zou kunnen worden zit je goed!
