### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by ashleyKeuning** [cmda-bt/be-course-20-21#29]
# Package

## Name
Ashley Keuning

## Class
Tech 3

## Repo link
https://github.com/ashleyKeuning/Matching-App.git 

## Summary
ik heb voor het eerst met de terminal gewerkt, ik heb een boilerplate gemaakt, een package.json toegevoegd.
verder heb ik express, nodemon en camelcase geïnstalleerd. als laatst heb ik een run script gemaakt en en .gitignore mapje aangemaakt.
ondertussen heb ik ook wat artikelen gelezen die werd gezet in de GitHub, als selfstudy.

## Resources used

- de les
- https://www.atlassian.com/git/tutorials/saving-changes/gitignore 
- https://react.design/terminal 

## Any thoughts?
ik vond het eerlijk gezegd best moeilijk voor een eerste keer, het was heel wat informatie in één keer,  maar na wat artikelen lezen en vragen stellen was het wel te doen doen. :)

**Comment by victorboucher** [comment]
Hi Ashley, ziet er netjes uit! Goed dat je ook het gitignore bestandje hebt gemaakt en hier je node modules en DS_Store bestand in hebt gezet. Ga zo door! 🥇
