### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by KathleenvanDam** [cmda-bt/be-course-20-21#32]
# Package

## Name
Kathleen van Dam

## Class
Tech3

## Repo link
https://github.com/KathleenvanDam/Tech-project

## Summary
Artikelen gelezen en daarna de video over nam packages bekeken. Vervolgens een package.json aangemaakt en via de terminal naar GitHub gepusht. Even gestunteld met run scripts en een .gitignore gecreëerd. Verder wist ik niet zo goed welke package ik moest instellen. Heb nodemon geïnstalleerd zoals in de video. 

## Resources used
https://www.pluralsight.com/guides/how-to-use-gitignore-file
https://www.freecodecamp.org/news/introduction-to-npm-scripts-1dbb2ae01633/ 
https://www.youtube.com/watch?v=shSB9BbK1gU 

## Any thoughts?
Momenteel heb ik nog geen idee wat de kracht is van die packages en weet ik niet goed wat ik nodig heb voor m'n applicatie. Daarom heb ik dat nu even gelaten voor wat het is. Ook vroeg ik me af of er een verschil zit in de terminal van vscode en de terminal van je laptop/pc zelf?

**Comment by SamSlotemaker** [comment]
Het is ook vooral verkennen momenteel, wanneer je straks de app gaat bouwen kom je vanzelf packeges tegen die nodig/tof zijn. Over de terminal, er is in principe geen verschil, vscode gebruikt simpelweg die van je computer. Je zelf kiezen in VScode welke terminal je wilt gebruiken, je kunt er zelfs meerdere tegelijk open hebben staan mocht dat handig zijn
