### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by Zaraschriever** [cmda-bt/be-course-20-21#34]
# Package

## Name
Zara Schriever

## Class
Tech 1

## Repo link
https://github.com/Zaraschriever/project-tech

## Summary
Ik heb voor deze week eerst de theorie gelezen en de filmpjes gekeken, ik snapte niet helemaal hoe de playground oefeningen werkte dus die heb ik over geslagen en ben gelijk naar de opdracht gegaan. Stap 1,2 en 3 ging dankzij Danny's filmpje erg goed de laatste stappen vond ik wat lastiger maar die zijn uiteindelijk ook gelukt.

## Resources used
- de theorie
- uitleg filmpjes van Danny
- https://www.youtube.com/watch?v=hHt3oVk3XVk

## Any thoughts?
Door het huiswerk ben ik de terminal wel veel beter gaan begrijpen, ik snap alleen nog steeds niet echt hoe we dit gaan gebruiken in het concept.

**Comment by SamSlotemaker** [comment]
Lekker bezig Zara! Was het ook gelukt met de package.json en de .gitignore? Wellicht ben je ze vergeten naar github te pushen dan :) 

Mocht het nog niet helemaal gelukt zijn kun je me altijd even een berichtje sturen, Marvin en ik zijn er om je te helpen! 

Over de terminal, op zich gebruik je deze inderdaad niet voor je concept, maar wel om je concept uiteindelijk te realiseren. De terminal is nodig om straks bijvoorbeeld je applicatie te starten, packages te installeren/updaten, en het pushen naar github.
