### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by AronPelgrim** [cmda-bt/be-course-20-21#35]
# Package

## Name
Aron Pelgrim

## Class
Tech 2

## Repo link
https://github.com/AronPelgrim/matching-application

## Summary
Ik ben begonnen met het lezen van de theorie om een beter beeld te krijgen van Node.js en waarvoor het dient. Vervolgens heb ik een package.json aangemaakt met de juiste metadata. Nadat dit was gelukt heb ik de package camelcase geinstalleerd. Ook heb ik nodemon geinstalleerd onder devDependencies en heb ik een .gitignore file aangemaakt om een specifieke map niet te pushen naar de repository. Als laatst heb ik de nieuwe bestanden gepusht naar git.

## Resources used
https://docs.github.com/en/github/importing-your-projects-to-github/adding-an-existing-project-to-github-using-the-command-line
https://rogerdudler.github.io/git-guide/index.nl.html
https://www.youtube.com/watch?v=ZpiHUOM_Y-0
https://www.youtube.com/watch?v=X8D5Ijpp824
https://www.youtube.com/watch?v=shSB9BbK1gU

## Any thoughts?
Het huiswerk was opzich goed te doen, het duurde bij mij alleen heel erg lang om de bestanden naar git te pushen via de terminal.

**Comment by TuriGuilano** [comment]
Nice Aron!
