### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by robbinux** [cmda-bt/be-course-20-21#38]
# Package

## Name
Robbin Jansen

## Class
Tech 3b

## Repo link
https://github.com/robbinux/matching-app-blocktech

## Summary
Het lijkt erop dat het is gelukt om Node en NPM succesvol te installeren. Ik heb in de package.json camelcase weten te installeren. Verder dan dat ben ik niet gekomen. Het lukte mij tevens niet om de code naar Github te pushen met de terminal. Ik hou de verschillende CLI nog erg door elkaar. Bash, cmd, powershell, Ubuntu, wat is het verschil en waar moet ik wat mee doen? Ik heb geen overzicht.

## Resources used

https://react.design/terminal
https://www.pluralsight.com/guides/how-to-use-gitignore-file
https://www.freecodecamp.org/news/introduction-to-npm-scripts-1dbb2ae01633/
https://nodejs.org/
https://www.npmjs.com/ 
https://www.youtube.com/watch?v=wrb7Gge9yoE

## Any thoughts?
We gaan naar mijn mening op het moment te snel. Ik houd het niet bij en ben het overzicht kwijt. Ik heb meer toelichting nodig over de CLI's en hoe ik nou het beste met Visual Studio Code kan werken in combinatie met Github. In sommige tutorials wordt de CLI daarbinnen gebruikt en soms niet. Hoe zit dit? Ik vraag mij af of dingen wel juist doe in VSC.

**Comment by victorboucher** [comment]
Hi Robbin, je repo is nog behoorlijk leeg. Ik mis eigenlijk alles nog van NPM. Laat het even weten in teams als je hier extra ondersteuning bij nodig hebt!
