### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by Mentalyzd** [cmda-bt/be-course-20-21#4]
# Package

## Name
Christiaan Zandbergen

## Class
Tech-1 a (212)

## Repo link
https://github.com/Mentalyzd/Blok_Tech/tree/main/back-end

## Summary
github gelinkt aan mijn editor en repo gecloned. Toen npm installaties gedaan van nodemon en camelcase enz. Daarna een nieuw script toegevoegd aan de package.json en uitgevoerd met nodemon.

## Resources used
https://github.com/cmda-bt/be-course-20-21/blob/main/week-1.md

## Any thoughts?
Was leuk maar er word nergens uitgelegd hoe je je github kan link bijvoorbeeld met ssh of anders.

**Comment by SamSlotemaker** [comment]
Goed bezig Christaan, zorg er nog even voor dat je een .gitignore aanmaakt, je pusht nu onnodige files (bijvoorbeeld alles in node_modules) en dit kan al gauw oplopen tot enorme groottes
