### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by Kuckelkorn** [cmda-bt/be-course-20-21#41]
# Package

## Name
Remco Kuckelkorn

## Class
TEC1

## Repo link
[Project Tech Repo](https://github.com/Kuckelkorn/hetwgtao)

## Summary
Because im taking a resit, i just looked at some of my packages i used for a previous project and selected a few I knew I'm going to need to use. 

## Resources used
Previous repositories 

## Any thoughts?
n/a

**Comment by SamSlotemaker** [comment]
top top
