### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by pmvdbijl7** [cmda-bt/be-course-20-21#43]
# Package

## Name
Patrick van der Bijl (500823037)

## Class
Tech 2b (204)

## Repo link
https://github.com/pmvdbijl7/matching-app

## Summary
Allereerst ben ik begonnen met het lezen van de artikelen die bij de theorie staan van week 1. Daarna ben ik zelf aan de slag gegaan met het vullen van mijn repository en het installeren van een paar packages. In eerste instantie deed ik dit allemaal in de code editor PhpStorm, omdat ik hier erg bekend mee ben. Echter lukte het mij niet om de Ubuntu terminal te gebruiken in PhpStorm, dus heb ik er toen toch voor gekozen om verder te gaan in VS Code wat wel allemaal goed werkte. Naast dit kleine probleempje heb ik gelukkig geen andere problemen gehad.

## Resources used
- https://nodejs.dev/learn/introduction-to-nodejs
- https://nodejs.dev/learn/differences-between-nodejs-and-the-browser
- https://nodejs.dev/learn/an-introduction-to-the-npm-package-manager
- https://zellwk.com/blog/frontend-vs-backend/
- https://www.youtube.com/watch?v=ZpiHUOM_Y-0
- https://www.youtube.com/watch?v=X8D5Ijpp824

## Any thoughts?
Ik heb al eerder met Git, GitHub en de terminal gewerkt dus ik had geen problemen met het huiswerk van deze week. Daarnaast vind ik de organisatie en informatie van het vak erg duidelijk en overzichtelijk. Dit is heel fijn om mee te werken.

**Comment by TuriGuilano** [comment]
Fijn dat je die switch hebt gemaakt naar VSC. Mooi dat alles verder goed gaat
