### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by babsluidinga** [cmda-bt/be-course-20-21#44]
# Package

## Name
Babs Luidinga

## Class
TECH-1

## Repo link
https://github.com/babsluidinga/blok-tech

## Summary
Voor Backend hebben we verschillende modules moeten installeren, om deze vervolgens te kunnen toepassen in onze applicatie. Ik heb me nu vooral gefocust op het stukje leren hoe ik via de terminal dingen moet installeren, aangezien ik hier nogal moeite mee had. Het toepassen in de applicatie vond ik nogal lastig dus daar heb ik nog vrij weinig mee gedaan. 

## Resources used
In mijn Wiki kan je mijn brongebruik zien, ik ben van plan om dit allemaal in 1 bestand te zetten naarmate ik wat meer bronnen heb, op dit moment is het nog niet echt nodig aangezien ik nog niet heel veel bestanden en documentatie in mijn wiki heb. 

## Any thoughts?
Ik vond het echt even lastig, snapte vrijwel niet wat ik moest doen, maar gelukkig was ik niet de enige en heb ik samen met medestudenten iets hebben kunnen maken.

**Comment by SamSlotemaker** [comment]
Fijn dat jullie er samen wat van konden maken, zo leer je het meest! Zorg er nog wel even voor dat je de .gitignore vult met bestanden die je niet op github wilt hebben, zoals de node_modules folder. Deze kan namelijk al erg snel oplopen tot enorme groottes. 
Mocht je vast komen te zitten kun je ook altijd mij en Marvin een berichtje sturen, wij zijn er ook om jullie te helpen!
