### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by TeunvK** [cmda-bt/be-course-20-21#45]
# Package

## Name

Teun van Kessel

## Class

Tech1

## Repo link

https://github.com/TeunvK/BlokTech

## Summary

Completed the Command Line tutorial
Code: **VGV1bnZLCg==**

## Resources used

https://github.com/LeCoupa/awesome-cheatsheets/blob/master/languages/bash.sh

## Any thoughts?

After a bit of trouble with the CL tutorial, I got it to work by moving the tutorial.sh file into the run directory.
Besides that it was a pretty easy to follow tutorial.

**Comment by SamSlotemaker** [comment]
Was je ook al toegekomen aan de rest van de opdrachten van week 1, zoals de packet.json en de .gitignore? Mocht dit nog niet het geval zijn, zou ik er voor zorgen dat je deze echt nog even bekijkt en afrond, want deze zijn cruciaal voor de aankomende weken!
