### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by Jortdus** [cmda-bt/be-course-20-21#49]
# Package

## Name
Jort Broekhof

## Class
Tech 2.1

## Repo link
https://github.com/Jortdus/blok-tech

## Summary
Ik heb gebruik gemaakt van de streamapi node module om van steam gebruikers informatie te kunnen request vanuit de steam API. Daarnaast heb ik gebruik gemaakt van prompt-sync, een module om input vanuit de gebruiker makkelijker te coderen. De gebruiker moet een steamcommunity link als input geven en het programma kan op dit moment bijvoorbeeld de meest recente games tonen in de terminal.

## Resources used
Stackoverflow
 [steamAPI](https://www.npmjs.com/package/steamapi)

**Comment by TuriGuilano** [comment]
Tof gedaan Jort, even je API key in je .env knallen - download dotenv en gooi je .env ook in je .gitignore
