### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by Kip-Hub** [cmda-bt/be-course-20-21#5]
# Package

## Name
Daniel Kip

## Class
Tech 1a

## Repo link
https://github.com/Kip-Hub/matching-app

## Summary
Camelcase en nodemon geinstalleerd (wat 200 folders aan node_modules toevoegt...?). Vervolgens in index.js met camelcase een console.log gemaakt, en scripts toegevoegd aan package.json. 
Tot slot heb ik uitgepluisd hoe ik VS Code met GitHub kan verbinden om vanuit de editor te kunnen committen en pushen (wat denk ik gelukt is)

## Resources used
De toelichtingsvideos van Danny op youtube

## Any thoughts?
Vrij pittig. Het voelt alsof ik maar wat doe, maar het schijnbaar wel werkt zoals de bedoeling is

**Comment by SamSlotemaker** [comment]
Zorg nog even voor een .gitignore, zodat je geen onnodige folders (zoals node_modules) meepusht naar github! Eigenlijk wat je zelf als zegt, deze folder kan al snel erg groot worden.
Dat er met 1 package meerdere folders binnen gehaald worden komt vaak doordat packages op zichzelf ook weer andere packages requieren en het zo een enorme trein aan dependencies kan worden. 

Laat je ook vooral niet van de wijs brengen door het feit dat het nu allemaal nog redelijk vaag is, in de loop der weken wordt het allemaal steeds iets duidelijker (:
