### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by mandemt** [cmda-bt/be-course-20-21#51]
# Package

## Name
Tom Mandemaker

## Class
209

## Repo link
https://github.com/mandemt/techblok

## Summary
package.json is aangemaakt
index.js is aangemaakt 
NPM package : chat geinstalleerd , wil hem weer verwijderen omdat ik er nu niks mee kan in javascript (te ingewikkeld) maar weet niet hoe te uninstallen.

npm package missionlog geinstalleerd
https://www.npmjs.com/package/@dung95/test123

**vanaf hier kreeg ik de error dat er geen write access in sommige folders is**
ik kon proberen met sudo install en dat werkte wel.

npm package less geinstalleerd
de package kan helpen om css blokken samen te voegen in een code
http://lesscss.org/

Nodemon dependency geinstalleerd

grund-cli dependency geinstalleerd

script gemaakt met hallo world
    "start":"echo 'hallo world'"

## Resources used
https://www.freecodecamp.org/news/introduction-to-npm-scripts-1dbb2ae01633/
https://nodejs.dev/learn/npm-global-or-local-packages
https://gruntjs.com/getting-started
https://www.npmjs.com/package/@dung95/test123

## Any thoughts?
ik snap echt niet hoe je kan vinden op de site van een package wat ik in javascript er mee kan doen.

**Comment by shabier** [comment]
Hi! Je kan NPM packages verwijderen door `npm uninstall <package name>` , dan wordt het van je computer en/of node_modules map verwijdert, zie [npm uninstall](https://docs.npmjs.com/cli/v6/commands/npm-uninstall).
