### ISSUE TITLE
Week 2

### ISSUE THREAD

**Issue by daoneandonly** [cmda-bt/be-course-20-21#52]
# Templating

## Name
Steven Whitton

## Class
TECH2b

## Repo link
https://github.com/daoneandonly/cmda-be

## Summary
* Use Express to handle the routes of `/`, `about` and `profile`
* Add Pug templating engine
* Add data is separate file
* Use conditionals in `about`
* Use mixins in the `header`
* Use a layout file for general HTML layout
* Use blocks and includes to render specific parts of the site
* Write out my thoughts on the different templating engines in my [wiki](https://github.com/daoneandonly/cmda-be/wiki/Templating-engines)

## Resources used
* [Pug Docs](https://pugjs.org/api/getting-started.html)

## Any thoughts?
Pug is life ❤️ 
![image](https://user-images.githubusercontent.com/14161179/107678479-beb20300-6c9b-11eb-979a-e0ea70996041.png)
[Source](https://www.reddit.com/r/AnimalsBeingDerps/comments/lfpae8/potatoes_gonna_potate/)

**Comment by Vuurvos1** [comment]
Good reasoning to choose Pug over the other templating engines, do make sure to commit often and consistent (8 days ago? you don't have to commit when a feature is perfect/done). I would say you are ready to connect a database to your project
