### ISSUE TITLE
Week 2

### ISSUE THREAD

**Issue by ashleyKeuning** [cmda-bt/be-course-20-21#58]
# Templating
Handlebars

## Name
Ashley Keuning

## Class
tech 3

## Repo link
https://github.com/ashleyKeuning/Matching-App.git

## Summary
added template engine handlebars

## Resources used
https://www.npmjs.com/package/express-handlebars

## Any thoughts?
ik vind het een beetje onduidelijk, de uitleg en alles, maar ik denk dat ik het wel oké heb

**Comment by victorboucher** [comment]
Netjes gedaan Ashley, ik zie dat je al over de users heen loopt in je Handlebars bestand. Misschien kun je wat extra users toevoegen zodat je dat resultaat kunt zien, aangezien je er nu maar eentje hebt staan in de array in je index.js bestand. Ik zie ook nog op veel plekken een .DS_Store bestand staan, deze zou je in je .gitignore willen hebben. Als het daar al in staat moet je ze even verwijderen uit je repo.
Je maakt bovenin je index.js bestand een variable 'port' aan. Maar die gebruik je nergens. Ik denk dat het netjes is als je deze nog even gebruikt op regel 61, dus ipv het getal '3000'. Verder zou je dan ook de console log daaronder aan kunnen passen met 'template literals', dan zou je dit kunnen doen: `Express web app on localhost:${port}`. Als je dan ooit de port aanpast wordt het overal aangepast. Dan hoef je dit maar op een enkele plek te veranderen. (denk niet dat je dat zomaar zou doen want dat heeft niet echt nut, maar het is wel gewoon good practice om dit op deze manier te doen).
