### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by DeefDeMeef** [cmda-bt/be-course-20-21#6]
# Package

## Name
Davey Zaal

## Class
Tech1 A (212)

## Repo link
https://github.com/DeefDeMeef/blok-tech/tree/main/back-end

## Summary
Ik heb node.js geprobeerd te gebruiken en dit helemaal geïnstalleerd op mijn laptop/GitHub. Ik heb Visual Studio Code gekoppeld aan Git en GitHub. Ook de Ubuntu terminal aan Visual studio code toegevoegd en een start script toegevoegd aan package.json om deze vervolgens uit te voeren in de terminal. Dit ging erg goed, het was wel lastig om alles met elkaar te verbinden en te weten wanneer nou iets was gekoppeld. Maar dat is goed gekomen door gewoon te blijven proberen. 

## Resources used
Ik heb de documentatie van GitHub en npm voornamelijk gebruikt om te me GitHub goed te koppelen. Verder de artikelen van het huiswerk uit deze week.

## Any thoughts?
Voor me gevoel werd ik lekker in het diepe gegooid, wat ik juist wel leuk vind. Denk dat ik op deze manier het beter leer dan dat alles helemaal staat uitgeschreven voor me, hiermee bedoel ik voornamelijk de problemen waar je tegen aan kan lopen. De basis uitleg was top om te kunnen starten.

**Comment by SamSlotemaker** [comment]
Goed bezig Davey, het diepe kun je het inderdaad wel noemen ja! Fijn dat dat goed gaat, voeg nog wel even een .gitignore toe :)
