### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by sarahverkade** [cmda-bt/be-course-20-21#60]
# Package

## Name
Sarah Karamat Ali

## Class
Tech 1a

## Repo link
https://github.com/sarahverkade/matching-application.git

## Summary
Ik vond het leuk om met de terminal te werken en begin er steeds beter in te worden. 
Het is me helder waar packages voor worden gebruikt en hoe ik ze via de terminal kan installeren. 
Ik heb geleerd te werken met Visual Studio Code & Atom (voorheen gebruikte ik nog brackets).

## Resources used
stackoverflow.com
https://docs.github.com/en
https://gist.github.com/poopsplat/7195274
npmjs.com
https://gist.github.com/substack/7567983

## Any thoughts?
Ik vond het heel erg fijn dat Danny video's had gemaakt. De voorbeelden in praktijk maakte dat ik de theorie iets beter begreep. De theorie was veel en omdat het nieuw was voor mij soms best moeilijk om alles te onthouden waardoor ik vergat waar en hoe ik moest beginnen. Verder vond ik dat alles goed werd uitgelegd en dat er een goede balans was tussen self-research en de stappen waar je bij werd geholpen. 
Ik merk dat ik het nog lastig vind om informatie te filteren dus; wat is belangrijk en wat kan ik weglaten? Bijvoorbeeld bij het gebruiken van packages en scripts. Welke files ga ik mee werken en welke moet ik negeren. Gitignore begrijp ik wel maar ik vind het nog lastig om te begrijpen welke files niet belangrijk zijn en waarom dan niet. Ook de mappen structuur in node_modules vind ik soms wat intimiderend.

**Comment by SamSlotemaker** [comment]
in de .gitignore komen eigenlijk alle files die niet belangrijk zijn, of die je simpelweg niet op github wilt hebben. node_modules is bijvoorbeeld een folder die snel oploopt in grootte, en automatisch gevuld wordt wanneer het command 'npm install' gerund wordt, deze download namelijk alle packages die jij bij je dependencies hebt staan in package.json, het is hierdoor dus niet nodig om deze bestanden steeds naar github te pushen. 
Ook zul je straks gaan werken met bijvoorbeeld inloggegevens van een database, informatie die je zeker niet op github wilt hebben staan, toegankelijk voor iedereen. 

De mappenstructuur van node_modules hoef je dus eigenlijk ook niet te begrijpen, dat doen de packages onderling zelf wel :)
