### ISSUE TITLE
Week 2

### ISSUE THREAD

**Issue by MichaelChorak** [cmda-bt/be-course-20-21#67]
# Templating

## Name
Michael Chorak

## Class
tech 3

## Repo link
https://github.com/MichaelChorak

## Summary
Installed express with NPM. After that we served our server and also installed nodemon so we dont have to reload the server after each edit. I did some research about the template engines and went for Handlebars.js and did make a small test round with some data in it and how it works.

## Resources used
https://handlebarsjs.com/guide/#custom-helpers
https://handlebarsjs.com/guide/#evaluation-context
Also got help from Sonja Rouwhorst with the setup of Handlebars

## Any thoughts?
Setting it up was do-able, not really complicated. But now we are at the part of using the template engine to create dynamic data. This is quite hard, it's mostly all new information for me, but its very interesting an fun to do.

**Comment by victorboucher** [comment]
Ziet er goed uit Michael. Ik zou wel nog even de pug en pug-cli dependencies verwijderen als je deze niet meer gaat gebruiken (dit doe je met 'npm uninstall [dependency naam]' in je terminal). Verder erg nice dat je al over een array met objecten (in dit geval films) heen loopt en deze allemaal weergeeft met Handlebars. Dit kun je later natuurlijk gebruiken om een lijst met gebruikers of matches oid te laten zien aan de gebruiker. Fijne structuur ook in je view folder, goed dat je verschillende dingen zoals je head, header en footer hebt opgesplitst. Dit zorgt er zeker voor dat alles overzichtelijker blijft!
