### ISSUE TITLE
Week 2

### ISSUE THREAD

**Issue by lottekoblens** [cmda-bt/be-course-20-21#68]
# Templating

## Name
Lotte Koblens

## Class
tech1

## Repo link
https://github.com/lottekoblens/matching-application

## Summary
Lastig om aan de slag te gaan met de templating engine. Lang bezig geweest om daadwerkelijk mijn application met de templating engine draaiende te krijgen. Uiteindelijk was de oplossing dat ik een main.handlebars file aanmaakte in de layouts folder, ik ben er nog niet helemaal achter waarom. Maar kon uiteindelijk gelukkig weer verder aan de slag met handlebars. 

## Resources used
- https://waelyasmina.medium.com/a-guide-into-using-handlebars-with-your-express-js-application-22b944443b65#:~:text=handlebars%20file%20(%E2%80%9Cmain.,you%20name%20it%20main%20though)
- https://handlebarsjs.com/
- https://www.npmjs.com/package/handlebars
- https://www.sitepoint.com/a-beginners-guide-to-handlebars/

## Any thoughts?
Ik vond het erg lastig om aan de slag te gaan met de templating engine. Snapte echt niet goed wat je er nou mee kon en wat je ervoor nodig had e.d. Ook veel moeite gehad met daadwerkelijk de engine werkende te krijgen, hulp gevraagd aan docent en aan een studentassistent (denk ik) die daar ook bij zat. Zij konden mij allebei ook niet helpen, waardoor ik de moed eigenlijk wel een beetje kwijt was. Toen hulp gevraagd aan iemand uit m'n eigen omgeving en het gelukkig toen voor elkaar gekregen. Daarna kreeg ik het niet voor elkaar om m'n css file te linken en was ik eigenlijk weer de moed kwijt, had het gevraagd in teams maar het was weekend dus daarom denk ik geen reactie gekregen. Uiteindelijk wel zelf kunnen oplossen, maar wel 2 middagen mee bezig geweest en dat vond ik dan weer zonde van m'n tijd aangezien het uiteindelijk iets heel eenvoudigs was.

**Comment by SamSlotemaker** [comment]
Heel irritant als zoiets kleins je zo veel tijd kost, probeer je er ook niet op stuk te kijken. Je kunt mij of Marvin altijd gewoon even een prive berichtje sturen en dan kunnen wij er ook even op ons gemak naar kijken. Snap je nu wel hoe het werkt en waarvoor je het nodig hebt? Stuur me anders alsnog even een berichtje!
