### ISSUE TITLE
Week 2

### ISSUE THREAD

**Issue by dannyfrelink** [cmda-bt/be-course-20-21#70]
# Templating

## Name
Danny Frelink

## Class
Tech 3a, 211

## Repo link
https://github.com/dannyfrelink/Blok-Tech

## Summary
Ik ben eerst bezig geweest met de research naar template engines. Hiervan heb ik een overzicht gemaakt van de top 7. Dit komt doordat Pug op nummer 7 stond en ik deze ook wilde bekijken, aangezien deze werd genoemd in de be-course repo. Hier kwam Mustache op 1 en Handlebars op 2. Aangezien ook Handlebars in de repo was genoemd en ik hier meer over kon vinden, besloot ik hiervoor te kiezen. Ik heb een main.handlebars en een profiel.handlebars aangemaakt en hier mijn eerder geschreven code aan toegevoegd. In main.handlebars heb ik de code neergezet die ik op alle pagina's terug wil laten komen.

Vervolgens heb ik gekeken naar een extra npm package om te kunnen gebruiken voor mijn concept. Ik vond de package 'countries-list' waar allerlei info per land over te vinden is. Deze heb ik gedownload en ik heb deze gerequired in mijn JS. Daarna heb ik ook geprobeerd om iets uit deze package te halen, maar dat is mij niet gelukt. Ik heb geprobeerd om bijvoorbeeld de naam van een land weer te laten geven, maar hij geeft op het moment niks weer.

Ik ben hier vastgelopen en kon daardoor ook niet echt lekker verder werken met dingen uitproberen, aangezien ik niet weet hoe ik dit aan de praat kan krijgen. Als iemand iets weet, hoor ik het graag.

## Resources used
Alle gekregen bronnen, 
https://colorlib.com/wp/top-templating-engines-for-javascript/ ,
npmjs.com/
https://github.com/annexare/Countries
https://handlebarsjs.com/guide/builtin-helpers.html#each

## Any thoughts?
Ik vond dit wederom erg lastig om allemaal zelf uit te gaan vogelen. Ik mis daar soms wel wat begeleiding in, aangezien het allemaal nieuw is en ik daardoor ook geen idee heb waar ik moet zoeken. Hierdoor zit ik er vaak veel langer aan dan dat er voor staat gegeven, waardoor andere vakken er ook onder lijden.

**Comment by shabier** [comment]
Hey! Ik zie dat je al lekker op weg bent! Ik heb naar countries-list package gekeken, je kan een land uit de lijst halen door te loopen op de values: `Object.values(countriesList.countries).find(key => key.name == 'Netherlands')`. Dan krijg je het object voor dat land:

```js 
{
  name: 'Netherlands',
  native: 'Nederland',
  phone: '31',
  continent: 'EU',
  capital: 'Amsterdam',
  currency: 'EUR',
  languages: [ 'nl' ],
  emoji: '🇳🇱'  ,
  emojiU: 'U+1F1F3 U+1F1F1'
}
```

Leesvoer: 
[Object.values()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/values)
[find()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find)

**Comment by dannyfrelink** [comment]
Thanks @sjagoori, ik heb het nu voor mekaar gekregen om alle landen erin te zetten. Dan wil ik later nog met een database alleen de gekozen antwoorden laten zien. 

Ik heb nog wel een vraagje. Hoe kan ik items die ik uit die package haal, stylen in mijn css. Moet ik dan dit doen 'p {} { styling hier }'?

**Comment by shabier** [comment]
Zo kan het idd, je zou ook nog een class kunnen toevoegen aan het element in je template
