### ISSUE TITLE
Week 2

### ISSUE THREAD

**Issue by jody29** [cmda-bt/be-course-20-21#76]
# Templating

## Name
Jody Lorist

## Class
Tech 2a

## Repo link
https://github.com/jody29/matching_feature/tree/main

## Summary
Ik heb de afgelopen week een templating engine gekozen. Ik heb uiteindelijk gekozen voor EJS. Dit is omdat de syntax van EJS erg overeenkomt met de syntax van PHP. Bij PHP gebruik je namelijk <?= variabel ?> en bij EJS <%= variabel %> om een dynamisch element te tonen op je html pagina. Ook heb ik een route bestand aangemaakt. Hierin heb ik alle verschillende routes gemaakt. Deze heb ik vervolgens geëxporteerd als module om deze module vervolgens weer op te roepen in mijn index.js.

Ook heb ik geprobeerd om de twitch gaming database API toe te voegen aan mijn app. Dit is helaas niet gelukt. Ik ben wel zover gekomen dat ik een acces token ontving uit mn terminal. Ik had een leeg variabel aangemaakt voor deze acces token en een functie aangemaakt die een acces token aanmaakt en vervolgens in dit variabel zet. Dit is alleen niet gelukt. Uiteindelijk heb ik het opgegeven en heb nu vooral de hoop dat we dit misschien in de loop van de komende weken gaan leren.

## Resources used
https://handlebarsjs.com/guide/#what-is-handlebars
https://ejs.co/
https://pugjs.org/api/getting-started.html
https://www.codecademy.com/learn <-- Hier heb ik express geleerd

## Any thoughts?
Ik heb deze week eigenlijk nergens echt moeite mee gehad. Ik denk dat ik goed op weg ben en misschien soms beetje te snel wil gaan. Ik heb namelijk nog nooit hiermee gewerkt, maar ik wil wel gewoon al alles kunnen nu. Goed voorbeeld is het al willen gebruiken van een API, terwijl ik dit nog nooit eerder heb gedaan. Als het dan niet lukt krijg ik het gevoel dat ik achter loop, terwijl als ik hoor wat anderen nog aan het doen zijn dan merk ik dat ik juist veel te ver vooruit loop.

**Comment by jonahgoldwastaken** [comment]
Hey Jody,

Goed bezig man. Je code is overzichtelijk en het lijkt erop dat je goed verstand van zaken hebt. We gaan helaas niet verder leren over het verbinden van APIs, alleen het opslaan van data in de database. Het valt eerlijk gezegd ook buiten het vak, dus je zal er op eigen houtje mee aan de slag moeten wil je dit voor elkaar krijgen.

Je zou anders een functionaliteit kunnen toevoegen waarbij gebruikers zelf games kunnen toevoegen aan je database, dan blijf je binnen de leerdoelen van het vak, en hoef je niet zelf een lijst aan te maken met games. Laat je dat lekker over aan de users. 😉 

Succes en fijne vakantie!
