### ISSUE TITLE
Week 2

### ISSUE THREAD

**Issue by norakramer1** [cmda-bt/be-course-20-21#83]
# Templating

## Name
Nora Kramer

## Class
Tech 1

## Repo link
https://github.com/norakramer1/blokTech

## Summary
Routing, 404, static files, pagina's gerenderd met de templating engine, begonnen met dynamische data renderen

## Resources used

- https://www.linkedin.com/learning/building-a-website-with-node-js-and-express-js-3/modular-routes-with-express-router?u=2132228
- https://www.youtube.com/watch?v=VM-2xSaDxJc&t=45s

## Any thoughts?
Geen vragen, ik ben nog niet ver gekomen met het maken van mijn matching app dus ik heb nog weinig gedaan met partials etc. De stof is verder wel duidelijk.

**Comment by SamSlotemaker** [comment]
Nou toppie dan!
