### ISSUE TITLE
Week 2

### ISSUE THREAD

**Issue by Sophievanderburg** [cmda-bt/be-course-20-21#84]
# Templating

## Name
Sophie van der Burg

## Class
Tech 2b

## Repo link
https://github.com/Sophievanderburg/blok-tech

## Summary
Ik ben lang bezig geweest met het huiswerk. De theorie die in de les behandeld werd vond ik veel. Daarom heb ik alle bronnen nog een paar keer gelezen. Ook heb ik extra bronnen gebruikt om de templating engines te begrijpen. 
Nadat ik dacht dat ik het ongeveer snapte ben ik met de opdrachten aan de gang gegaan. Tijdens deze opdrachten was google mijn grootste vriend :) . Met hulp van google en klasgenoten ben ik eruit gekomen. Ik kan wat dysnamische data meegeven in mijn ejs bestand. 
Ik ben nog niet heel ver met het uitbouwen van mijn feature, maar ik denk dat ik dat komende week wel inhaal.

Kortom: Na heel veel frustratie en proberen is het denk ik gelukt. 

## Resources used
Ik heb de bronnen gebruikt van: https://github.com/cmda-bt/be-course-20-21/blob/main/week-2.md

Eigen bronnen:
Pug
* https://www.linkedin.com/pulse/pugjs-basics-sondra-coffin/
* https://codingshala.com/pug-tutorial/

EJS
* https://medium.com/@atingenkay/getting-started-with-ejs-28fe4a693e53
* https://www.digitalocean.com/community/tutorials/how-to-use-ejs-to-template-your-node-application
* https://stackoverflow.com/questions/53025160/how-ejs-template-is-loaded-on-browser-how-frontend-interact-with-backend
* https://www.youtube.com/watch?v=RgAseumFyg8

Handlebars
* https://handlebarsjs.com/installation/
* https://www.geeksforgeeks.org/how-to-setup-handlebars-view-engine-in-node-js/

## Any thoughts?
Ik vind dit vak behoorlijk lastig. Alles is nieuw en behoorlijk abstract. In de lessen wordt in 50 minuten heel veel informatie gegeven en dan moet je zelf aan de slag. Ik snap dat het de bedoeling is dat we zelf dingen uitzoeken, maar dit vind ik toch best lastig.

**Comment by jonahgoldwastaken** [comment]
Hey Sophie,

Goed om te horen dat je er uiteindelijk uit bent gekomen, en dat je goede vrienden bent geworden met Google. Dat is een vriendschap die je je hele leven lang zal moeten koesteren. Netjes dat je nog op eigen onderzoek uit bent gegaan om alles echt goed te begrijpen, en je zo een bewuste keuze hebt kunnen maken in templating engine.

Je code is echt heel goed georganiseerd. Netjes dat je je route function onder je routes hebt staan. Zo kan ik lekker snel en overzichtelijk wisselen tussen wat welke route precies doet.

Ga vooral zo door, je bent lekker op weg! 👍🏻
