### ISSUE TITLE
Week 2

### ISSUE THREAD

**Issue by Hoa0** [cmda-bt/be-course-20-21#85]
# Templating

## Name

Thuan-Hoa Le
## Class

Tech 3
## Repo link

https://github.com/Hoa0/project-tech
## Summary

Voor dit vak liep ik een weekje achter, omdat ik later ben begonnen. Ik heb node.js en npm installaties volgens de opdrachten uitgevoerd en dit toegepast bij mijn project-tech. Verder heb ik alle theorie doorgenomen en live demo's (route) van de lessen opnieuw bekeken en ermee geoefend. Voor nu ben ik nog aan het uitzoeken welke template engine ik wil gaan gebruiken.

## Resources used

https://nodejs.dev/learn/introduction-to-nodejs
https://nodejs.dev/learn/an-introduction-to-the-npm-package-manager 
https://www.youtube.com/watch?v=ZpiHUOM_Y-0
https://www.freecodecamp.org/news/introduction-to-npm-scripts-1dbb2ae01633/ 
https://www.sitepoint.com/a-beginners-guide-to-pug/  
https://www.npmjs.com/package/express-handlebars
https://github.com/tj/ejs

## Any thoughts?

Het huiswerk voor week 2 vond ik wel wat lastiger, omdat template engine helemaal nieuw is voor mij en er zijn zoveel templates die je kan gebruiken. Hiervoor moest ik veel onderzoeken gaan doen, wat je ermee kan en hoe je dit moet toepassen.

**Comment by victorboucher** [comment]
Hoppaaa, je hebt in de tussentijd gewoon al een templating engine gekozen en hiermee data gerendered die je meegeeft via een route met Express! Netjes gedaan hoor, ziet er goed uit. Ga zo door! 🎈
