### ISSUE TITLE
Week 2

### ISSUE THREAD

**Issue by Kip-Hub** [cmda-bt/be-course-20-21#86]
# Templating

## Name
Daniel Kip

## Class
Tech 1a

## Repo link
https://github.com/Kip-Hub/matching-app

## Summary
Ik heb me eerst verdiept in Express, en het serveren van statische html pagina's.

Daarna heb ik gekeken naar de verschillende templating engines die te gebruiken zijn, en gekozen voor EJS (de research naar de alternatieven is te vinden in mijn wiki). Vervolgens ben ik aan de slag gegaan met het renderen van pagina's, het includen van partials zoals een head enzo, en het tonen van dynamische data op de betreffende pagina.  

## Resources used
https://ejs.co/   
https://www.youtube.com/watch?v=VM-2xSaDxJc  
https://www.youtube.com/watch?v=lY6icfhap2o

## Any thoughts?
De **serve** opdracht was niet erg lastig. De **templating** opdracht was een stuk lastiger, vooral als het gaat om dynamische data doorsturen.  
Verder merk ik dat ik nog goed moet nadenken over mijn feature, en hoe ik deze uit wil werken...

**Comment by SamSlotemaker** [comment]
In je github geef je aan dat je de dependencies los kunt installeren, maar hier komt die package.json goed van pas.
Wanneeer iemand jouw repo cloned en de command 'npm install' runt, kijkt npm welke dependencies er in de package.json staan en installeert deze direct allemaal. Hierdoor is simpelweg 1 keer 'npm install' genoeg voor alle dependencies (hierdoor is het ook belangrijk om dependencies uit package.json te verwijderen wanneer je deze geinstalleerd hebt maar niet meer nodig hebt).

Ziet er verder netjes uit, Daniel!
