### ISSUE TITLE
Week 2

### ISSUE THREAD

**Issue by pmvdbijl7** [cmda-bt/be-course-20-21#87]
# Templating

## Name

Patrick van der Bijl

## Class

Tech 2b (204)

## Repo link

https://github.com/pmvdbijl7/matching-app

## Summary

In deze tweede week ben ik begonnen met het lezen en kijken van de artikelen en videos over Express. Daarna heb ik Express geïnstalleerd in mijn repository en ben ik begonnen met wat basis routes en een error route. Ook heb ik de static files directory bepaald in mijn `app.js`.
Vervolgens ben ik aan de gang gegaan met een templating engine. Ik heb ervoor gekozen om Handlebars te gebruiken, omdat ik dit het meest op React vindt lijken. Ik ben namelijk erg bekend met React. Met Handlebars heb ik een aantal views gemaakt en dynamische data ingeladen.

## Resources used

+ https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/Introduction#introducing_express
+ http://expressjs.com/en/guide/routing.html
+ http://expressjs.com/en/guide/using-template-engines.html
+ https://www.youtube.com/watch?v=SRHQ3FM39Qg
+ https://www.youtube.com/watch?v=IS3HRyUXJX0

## Any thoughts?

Deze week verliep over het algemeen erg goed omdat ik niet tegen problemen ben aangelopen. Het was in het begin nog wel even uitzoeken hoe ik Handlebars moest gebruiken, maar dat ging gelukkig allemaal goed.

**Comment by jonahgoldwastaken** [comment]
Hey Patrick,

Lekker bezig kerel. Het lijkt erop dat je Express en Handlebars al goed onder knie begint te krijgen. Ik weet uit ervaring dat de Handlebars documentatie niet al te duidelijk is soms, dus het is goed om te zien dat het je allemaal goed af gaat.

Ga vooral zo door, heb hier eigenlijk niets op aan te merken.
