### ISSUE TITLE
Week 2

### ISSUE THREAD

**Issue by Zaraschriever** [cmda-bt/be-course-20-21#89]
# Templating

## Name
Zara Schriever

## Class
Tech 1

## Repo link
https://github.com/Zaraschriever/project-tech

## Summary
Deze week de theorie doorgelezen en de video's gekeken. Daarna een server aan gemaakt met Express en verschillende routes aan gemaakt. Gekozen voor de templating handlebars, dit vond ik wel even lastig dus daar ben ik nog niet helemaal klaar mee.

## Resources used
- filmpjes van week 2
- https://www.youtube.com/watch?v=erfN7fH7A6s&list=PLurIMwd6GdCi3ssXNAcjZ2l5mYaTfYPhf&index=1

## Any thoughts?
Ik vond het huiswerk wel weer lastig en heb er ook best wat tijd in zitten. Als ik iets niet snap vindt ik het moeilijk om een vraag te stellen omdat ik vaak dan niet echt snap wat ik niet snap.

**Comment by SamSlotemaker** [comment]
Niet snappen wat je niet snapt is ook iets niet snappen! Je kunt mij en Marvin altijd gewoon even een berichtje sturen, al is het maar om je even op weg te helpen of om samen uit te zoeken waar je de draad bent kwijt geraakt, het kan allemaal best intimiderend zijn namelijk!

**Comment by SamSlotemaker** [comment]
Probeer ook nog even te kijken naar de structuur van je files en mappen. Je hebt nu een server.js en een app.js, de server.js lijkt me vervolgensmij verouderd en dubbel, en de app.js staat in de public folder, deze zou ik hier buiten laten. Je zou even naar wat voorbeelden van anderen uit je klas kunnen kijken, hoe zij dit aanpakken! Er is geen 100% juiste manier, maar het is fijn om hier voor jezelf een structuur in te vinden.
