### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by lottekoblens** [cmda-bt/be-course-20-21#9]
# Package

## Name
Lotte Koblens

## Class
Tech1

## Repo link
https://github.com/lottekoblens/matching-application

## Summary
package.json file aangemaakt, daarna heb ik camelcase en nodemon packages geïnstalleerd. 
Toen met behulp van een start script index.js laten uitvoeren en ondervonden dat camelcase goed werkt.

## Resources used
Danny even om hulp gevraagd met de run scripts, omdat ik niet goed begreep wat deze deden.
Verder heb ik de video's van Danny gekeken en heb ik de documentatie bij de packages gebruikt.
De bron van de npm scripts heb ik ook geraadpleegd.

## Any thoughts?
Ik vond de run scripts wel lastig en kwam er niet uit met de bronnen die erbij stonden.

**Comment by SamSlotemaker** [comment]
Goed bezig Lotte, top dat het toch gelukt is met de scripts! 
Laat je ook zeker niet intimideren door de code documentatie, die kan soms een stuk ingewikkelder en uitgebreider zijn dan voor jou relevant is. Richt je vooral op zaken die jij nodig hebt in jouw project, dan kun je je kennis altijd nog verbreden wanneer dat gelukt is (: 

Mocht je ergens niet uit komen zijn Marvin en ik er ook om je te helpen, dus schroom niet om ons om hulp te vragen, als is het maar om de kleinste dingen, succes!
