### ISSUE TITLE
Week 2

### ISSUE THREAD

**Issue by christiaanbraun** [cmda-bt/be-course-20-21#90]
# Templating

## Name
Christiaan Braun

## Class
Tech_2a

## Repo link
https://github.com/christiaanbraun/find_a_teammate

## Summary
I'm starting to understand the whole node js server thing so that's nice. Furthermore I worked on server dynamic pages and I think that's working out quite nice. I can work with partials and routing works :). Pretty good week for me. 

## Resources used
https://www.geeksforgeeks.org/how-to-use-ejs-in-javascript/

https://github.com/mde/ejs/wiki/Using-EJS-with-Express

https://expressjs.com/en/guide/using-template-engines.html

ejs.co

## Any thoughts?
I had a lot of fun :).

**Comment by Vuurvos1** [comment]
- Ik weet niet of ik mijn email in mijn readme zou zetten. Ik zou eerder de mensen met vragen en opmerkingen naar de github issues sturen (en hier ook issue templates voor maken), Als mensen dan dezelfde vragen hebben kun je naar de bijbehoorende issue wijzen. 
- Ik zou ook nog wat kijken naar de consistentie van je code kijken ik zie [hier](https://github.com/christiaanbraun/find_a_teammate/blob/main/controller/controller.js#L10) bijvoorbeeld een random `n` staan en het is niet consistent ingesprongen. Om je te helpen met code consistensy zijn er linters, kijk hier even naar deze zijn erg handig zeker als je met meerdere aan een project gaat werken. 
- Verder zie ik ook nog de `node_modules` folder in je repo terwijl deze folder wel netjes in je `.gitignore` staat, kijk even naar [deze](https://stackoverflow.com/questions/50675829/remove-node-modules-from-git-in-vscode) stackoverflow post om dit te fixen

Verder goed bezig, ga zo door!
