### ISSUE TITLE
Week 2

### ISSUE THREAD

**Issue by Aidan98** [cmda-bt/be-course-20-21#91]
# Templating

## Name
Aidan Omwando

## Class
Tech 3

## Repo link
https://github.com/Aidan98/pt-backend

## Summary
Chose EJS as my templating engine, can't seem to link my css to my index.ejs file.

## Resources used
https://stackoverflow.com/questions/18629327/adding-css-file-to-ejs
https://ejs.co/#install

## Any thoughts?
It's easy to get lost during this assignment

**Comment by shabier** [comment]
Lekker bezig! Je css werkt, je moet nog even goed kijken naar je css; zodra je flex inzet of absolute kan je body niet doorgroeien
