### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by Ch3relle** [cmda-bt/be-course-20-21#92]
# Package

## Name
Cherelle

## Class
Tech 1

## Repo link
https://github.com/Ch3relle/pt-matching-app

## Summary
Ik heb een package.json file en .gitignore file aangemaakt.

## Resources used
https://www.youtube.com/watch?v=shSB9BbK1gU
https://www.freecodecamp.org/news/gitignore-what-is-it-and-how-to-add-to-repo/

## Any thoughts?

Het was te doen. Heb .gitignore alleen ietsjes later aangemaakt waardoor een stukje van node_modules op m'n repo in Github staat.

**Comment by SamSlotemaker** [comment]
Hey Cherelle :) 
Met onderstaande manier kun je er voor zorgen dat je een bestand/map van je repo verwijderd, maar deze lokaal wel blijft bestaan, zolang hij dan de volgende keer in je .gitignore staat is ie weg van github. 

https://stackoverflow.com/questions/3469741/remove-file-from-the-repository-but-keep-it-locally
