### ISSUE TITLE
Week 2

### ISSUE THREAD

**Issue by Jortdus** [cmda-bt/be-course-20-21#94]
# Templating

## Name
Jort Broekhof

## Class
Tech 2

## Repo link
https://github.com/Jortdus/blok-tech

## Summary
Did some research regarding templating engines and set up an expres server.

## Resources used
https://stackoverflow.com/
https://expressjs.com/
https://ejs.co/
[Why EJSvsHandlebars](https://www.codementor.io/@kishandevaliya/why-use-ejs-template-engine-with-expressjs-instead-of-handlebars-15tc0hiefq)

## Any thoughts?
Had to catch up on homework

**Comment by jonahgoldwastaken** [comment]
Hey Jort! Lekker bezig man. Ik zie dat je goed op weg bent met EJS. De volgende stap zou partials en daarna (eventueel) helpers zijn, dan heb je het helemaal onder de knie! 💪🏻 

Ik mis alleen nog een duidelijke conclusie voor je onderbouwing waarom je voor EJS bent gegaan. Ik kan het vaag afleiden uit je verhaaltje, maar het zou chill zijn als daar nog wat aandacht aan besteed wordt.
