### ISSUE TITLE
Week 2

### ISSUE THREAD

**Issue by sarahverkade** [cmda-bt/be-course-20-21#98]
# Templating

## Name
Sarah Karamat ali

## Class
Tech 1a
## Repo link
https://github.com/sarahverkade/matching-application.git

## Summary
Ik vond het deze week wel wat lastiger. Ik heb zeker wel meer dan 10 uur besteed aan het lezen van informatie over ejs en 20 uur aan het uitproberen van routes en conditionals. Ik liep ook vaak tegen kleine probleempjes aan zoals het niet werkend krijgen van routes via de server maar uiteindelijk is het wel gelukt. Ik ben nog aan het zoeken naar hoe ik met ejs een select menu kan maken en de variabele van de server terug kan halen. Ik kom vooral veel informatie tegen op het internet over mongodb maar volgens mij is het de bedoeling dat ik het eerst zonder werkend krijg. De conditionals moet ik dus nog even mee klooien. Includes met ejs vond ik wel eenvoudig. Wat ik nog niet helemaal begrijp is waarom mijn stylesheets niet apart worden ingeladen. De header.ejs is gekoppeld aan header.css maar neemt ook de styles over van mijn profile.css. Volgens mij zie ik iets over het hoofd. Al met al vind ik de opdrachten wel heel erg leuk. Ik loop wel achter met het huiswerk en dacht alles in te kunnen halen deze vakantie maar daar heb ik me in vergist. De tijd die er voor staat heb ik zeker x3 nodig dus ik ga het druk krijgen de komende week. 

## Resources used
https://ncoughlin.com/posts/express-ejs-render-page-dynamic-content/
https://medium.com/@adamzerner/how-bodyparser-works-247897a93b90
https://medium.com/@henslejoseph/ejs-partials-f6f102cb7433
https://ejs.co/#install
https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/forms
https://levelup.gitconnected.com/render-dynamic-content-in-nodejs-using-templates-a58cae681148

## Any thoughts?
Ik vond het lastig om de switch te maken van js naar ejs. Ik vond het ook moeilijk om zelf een multi-select dropdown te maken met ejs. Ik ben nog niet helemaal bekend met welke parameters ik kan gebruiken. Ik heb veel tijd besteed aan het zoeken van voorbeelden en het begrijpen van theorie. Ook liep soms tegen hele stomme kleine foutjes aan in m'n code waardoor iets ineens niet meer werkte maar goed dat hoort erbij. Wel jammer dat het me allemaal zoveel tijd heeft gekost.

**Comment by SamSlotemaker** [comment]
Lijkt er in iedergeval op dat je de basis werkend hebt gekregen! Een nieuwe syntax leren is altijd even zoeken inderdaad, maar dat is simpelweg een kwestie van oefenen, mocht je ergens niet uitkomen kun je mij en Marvin altijd even een berichtje sturen!
